export const API_URL = import.meta.env.VITE_API_URL
export const JWT_SECRET = '123456' as string
export const GRAPHQL_URL = import.meta.env.VITE_GRAPHQL_URL
export const WS_URL = import.meta.env.VITE_WS_URL
export const AZURE_CLIENT_ID = import.meta.env.VITE_AZURE_CLIENT_ID
export const AZURE_TENANT_ID = import.meta.env.VITE_AZURE_TENANT_ID
export const REST_API_URL = import.meta.env.VITE_REST_API_URL
export const DASHBOARD_LATITUDE = import.meta.env.VITE_DASHBOARD_LATITUDE
export const DASHBOARD_LONGITUDE = import.meta.env.VITE_DASHBOARD_LONGITUDE
